### ISSUE TITLE
 No module named 'safetensors._safetensors_rust'

### ISSUE THREAD

**Issue by LinHoujie** [Rahman-Motiur/MIST#2]
C:\ProgramData\anaconda3\envs\yolo\python.exe H:\MIST-main\Synapse_train.py 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\yolo\lib\site-packages\transformers\utils\import_utils.py", line 1472, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\ProgramData\anaconda3\envs\yolo\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\ProgramData\anaconda3\envs\yolo\lib\site-packages\transformers\modeling_utils.py", line 46, in <module>
    from .pytorch_utils import (  # noqa: F401
  File "C:\ProgramData\anaconda3\envs\yolo\lib\site-packages\transformers\pytorch_utils.py", line 19, in <module>
    from safetensors.torch import storage_ptr, storage_size
  File "C:\ProgramData\anaconda3\envs\yolo\lib\site-packages\safetensors\__init__.py", line 2, in <module>
    from ._safetensors_rust import (  # noqa: F401
ModuleNotFoundError: No module named 'safetensors._safetensors_rust'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\MIST-main\Synapse_train.py", line 17, in <module>
    from lib.networks import MIST_CAM
  File "H:\MIST-main\lib\networks.py", line 14, in <module>
    from decoders import CASCADE_Add, CASCADE_Cat
  File "C:\ProgramData\anaconda3\envs\yolo\lib\site-packages\decoders\__init__.py", line 1, in <module>
    from .binary_transformer import BinaryCodeTransformer, BinaryCodeTransformerConfig, batched_bin_vec_to_decimal, decimal_to_bin_vec
  File "C:\ProgramData\anaconda3\envs\yolo\lib\site-packages\decoders\binary_transformer.py", line 3, in <module>
    from transformers import PreTrainedModel, PretrainedConfig
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "C:\ProgramData\anaconda3\envs\yolo\lib\site-packages\transformers\utils\import_utils.py", line 1462, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\ProgramData\anaconda3\envs\yolo\lib\site-packages\transformers\utils\import_utils.py", line 1474, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
No module named 'safetensors._safetensors_rust'

Process finished with exit code 1
![{4EC7646F-6F9A-4055-90BB-7D59EF0DD436}](https://github.com/Rahman-Motiur/MIST/assets/132760640/a1691410-a9c1-4544-a77b-739c7d1776cd)

**Comment by danny-zhu** [comment]
Using safetensors==0.4.2 can solve the problem.
